"""Validate the ADR front matter and keep docs/adr/README.md's index derived from it.

An ADR is the durable memory of *why* a constraint exists, and this project is written
mostly by AI across sessions with no shared memory (CLAUDE.md 13). That makes two
failure modes expensive in a way they would not be elsewhere:

- **A hand-maintained index drifts.** A reader who consults the index, finds an answer
  and stops looking is worse off than one who found no index at all. So the table is
  generated from the files, and a stale table fails CI.
- **A supersession that only one side records** leaves two live, contradictory
  decisions in the tree with nothing saying which won. `superseded_by` and `supersedes`
  must agree, in both directions, or the record cannot be read.

Numbers may have gaps: 0013 is reserved for #21 and 0014 was written ahead of the
sequence. Demanding contiguity would block exactly the reservation the README makes.

Front matter is parsed with a small line reader rather than a YAML library. The block
is a fixed set of scalar keys written from one template, PyYAML is not a dependency of
this project, and adding one so a check can read ten lines is a dependency added for a
linter. The parser is deliberately strict: anything it does not recognise is reported,
never guessed at.
"""

from __future__ import annotations

import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Final

# The generated table lives between these. Everything outside them is hand-written
# prose that --write must not touch: the process explanation in that README is the
# part a reader actually needs, and a generator that owned the whole file would
# delete it on the first run.
INDEX_BEGIN: Final[str] = "<!-- adr-index:begin -- generated by tools/checks/adr_index.py -->"
INDEX_END: Final[str] = "<!-- adr-index:end -->"

FILENAME_PATTERN: Final[re.Pattern[str]] = re.compile(r"\A(\d{4})-[a-z0-9]+(?:-[a-z0-9]+)*\.md\Z")
SUPERSEDED_STATUS: Final[re.Pattern[str]] = re.compile(r"\Asuperseded by ADR-(\d{4})\Z")
ADR_REFERENCE: Final[re.Pattern[str]] = re.compile(r"\AADR-(\d{4})\Z")

REQUIRED_KEYS: Final[tuple[str, ...]] = (
    "number",
    "title",
    "date",
    "status",
    "supersedes",
    "superseded_by",
)


@dataclass(frozen=True, slots=True)
class AdrRecord:
    """One decision record's machine-readable header."""

    number: int
    title: str
    date_utc: date
    status: str
    supersedes: int | None
    superseded_by: int | None
    filename: str


def _front_matter_lines(source: str, *, filename: str) -> tuple[list[str], list[str]]:
    """(lines between the fences, failures). Returned as a pair rather than a union so
    that a front-matter line which happens to look like a failure message cannot be
    mistaken for one."""
    lines = source.splitlines()
    if not lines or lines[0].strip() != "---":
        return [], [f"{filename}: no front matter -- the file must open with a `---` fence"]
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return lines[1:index], []
    return [], [f"{filename}: front matter is opened but never closed"]


def _parse_reference(raw: str, *, key: str, filename: str) -> tuple[int | None, list[str]]:
    """`ADR-0002` -> 2, `null` -> None. Anything else is a failure, never a guess."""
    if raw == "null":
        return None, []
    match = ADR_REFERENCE.match(raw)
    if match is None:
        return None, [f"{filename}: {key} is {raw!r}; expected `ADR-NNNN` or `null`"]
    return int(match.group(1)), []


def parse_front_matter(source: str, *, filename: str) -> AdrRecord | list[str]:
    """Parse one ADR's header, or return every reason it could not be parsed.

    Returns all failures rather than the first, so a malformed header costs one round
    trip instead of one per field.
    """
    lines, fence_failures = _front_matter_lines(source, filename=filename)
    if fence_failures:
        return fence_failures

    fields: dict[str, str] = {}
    for line in lines:
        key, separator, raw = line.partition(":")
        if separator and not key.startswith(" "):
            fields[key.strip()] = raw.strip()

    failures = [
        f"{filename}: front matter is missing `{key}`" for key in REQUIRED_KEYS if key not in fields
    ]
    if failures:
        return failures

    number_raw = fields["number"]
    if not number_raw.isdigit():
        failures.append(f"{filename}: number is {number_raw!r}; expected four digits")

    try:
        parsed_date = date.fromisoformat(fields["date"])
    except ValueError:
        failures.append(f"{filename}: date is {fields['date']!r}; expected yyyy-mm-dd")
        parsed_date = date.min

    status = fields["status"]
    superseded_status = SUPERSEDED_STATUS.match(status)
    if status not in {"proposed", "accepted"} and superseded_status is None:
        failures.append(
            f"{filename}: status is {status!r}; expected `proposed`, `accepted` "
            f"or `superseded by ADR-NNNN`"
        )

    supersedes, supersedes_failures = _parse_reference(
        fields["supersedes"], key="supersedes", filename=filename
    )
    superseded_by, superseded_by_failures = _parse_reference(
        fields["superseded_by"], key="superseded_by", filename=filename
    )
    failures.extend(supersedes_failures)
    failures.extend(superseded_by_failures)

    # The status line is what a human reads and the field is what the index reads.
    # Letting them disagree means the rendered index can say `accepted` about a record
    # whose own first screen says it was replaced.
    if superseded_status is not None:
        named = int(superseded_status.group(1))
        if superseded_by != named:
            failures.append(
                f"{filename}: status names ADR-{named:04d} but superseded_by is "
                f"{'null' if superseded_by is None else f'ADR-{superseded_by:04d}'}"
            )
    elif superseded_by is not None:
        failures.append(
            f"{filename}: superseded_by is set but status is {status!r}; "
            f"a superseded record says so on its status line"
        )

    if failures:
        return failures

    return AdrRecord(
        number=int(number_raw),
        title=fields["title"],
        date_utc=parsed_date,
        status=status,
        supersedes=supersedes,
        superseded_by=superseded_by,
        filename=filename,
    )


def render_index(records: Sequence[AdrRecord]) -> str:
    """The index table, ordered by number. Trailing newline included."""
    rows = [
        "| # | Title | Date | Status |",
        "|---|---|---|---|",
        *(
            f"| [{record.number:04d}]({record.filename}) | {record.title} "
            f"| {record.date_utc.isoformat()} | {record.status} |"
            for record in sorted(records, key=lambda item: item.number)
        ),
    ]
    return "\n".join(rows) + "\n"


def _cross_reference_failures(records: Sequence[AdrRecord]) -> list[str]:
    by_number = {record.number: record for record in records}
    failures: list[str] = []
    for record in sorted(records, key=lambda item: item.number):
        if record.superseded_by is None:
            continue
        successor = by_number.get(record.superseded_by)
        if successor is None:
            failures.append(
                f"{record.filename}: superseded_by names ADR-{record.superseded_by:04d}, "
                f"which does not exist"
            )
        elif successor.supersedes != record.number:
            failures.append(
                f"{successor.filename}: supersedes should be ADR-{record.number:04d} because "
                f"{record.filename} says it was superseded by ADR-{successor.number:04d}"
            )
    return failures


def _index_failures(adr_root: Path, records: Sequence[AdrRecord], *, write: bool) -> list[str]:
    readme = adr_root / "README.md"
    if not readme.exists():
        return [f"{readme}: the ADR index is missing"]

    source = readme.read_text(encoding="utf-8")
    begin = source.find(INDEX_BEGIN)
    end = source.find(INDEX_END)
    if begin == -1 or end == -1 or end < begin:
        return [
            f"{readme}: the generated index sentinels are missing; the table must sit "
            f"between {INDEX_BEGIN!r} and {INDEX_END!r}"
        ]

    expected = render_index(records)
    current = source[begin + len(INDEX_BEGIN) : end].lstrip("\n")
    if current == expected:
        return []
    if write:
        readme.write_text(
            source[: begin + len(INDEX_BEGIN)] + "\n" + expected + source[end:],
            encoding="utf-8",
        )
        return []
    return [
        f"{readme}: the index is stale -- regenerate it with "
        f"`uv run python tools/checks/adr_index.py --write docs/adr`"
    ]


def check_tree(adr_root: Path, *, write: bool = False) -> list[str]:
    """Every reason this ADR directory cannot be trusted, in reporting order."""
    failures: list[str] = []
    records: list[AdrRecord] = []
    seen: dict[int, str] = {}

    for path in sorted(adr_root.glob("*.md")):
        if path.name == "README.md":
            continue
        match = FILENAME_PATTERN.match(path.name)
        if match is None:
            failures.append(f"{path.name}: filename must match NNNN-<kebab-slug>.md")
            continue

        parsed = parse_front_matter(path.read_text(encoding="utf-8"), filename=path.name)
        if isinstance(parsed, list):
            failures.extend(parsed)
            continue

        if parsed.number != int(match.group(1)):
            failures.append(
                f"{path.name}: front matter says number {parsed.number:04d} but the "
                f"filename says {match.group(1)}"
            )
            continue

        # Numbers are never reused (docs/adr/README.md). Two records sharing one means
        # a cross-reference to that number resolves to whichever the reader opened.
        if parsed.number in seen:
            failures.append(
                f"{path.name}: number {parsed.number:04d} is reused -- already held by "
                f"{seen[parsed.number]}"
            )
            continue

        seen[parsed.number] = path.name
        records.append(parsed)

    failures.extend(_cross_reference_failures(records))

    # A generator run over a tree with structural failures writes a confident index for
    # a record set that is already known to be wrong, and the write hides the failure
    # behind a green-looking file. Repair only what is otherwise sound.
    failures.extend(_index_failures(adr_root, records, write=write and not failures))
    return failures


def main(argv: Sequence[str]) -> int:
    write = "--write" in argv
    roots = [argument for argument in argv if argument != "--write"]
    failures: list[str] = []
    for root in roots:
        failures.extend(check_tree(Path(root), write=write))
    for failure in failures:
        print(failure, file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
