"""Engine, cost model and validation. Knows about simulated venues and historical
clocks.

Backtest and live share one code path; only the `ExecutionVenue` swaps. If a strategy
could behave differently here than on the demo account, every result this module
produces would be unfalsifiable.

Cost model parameters are calibrated from production market archives, never from
testnet -- testnet's measured spread is roughly fifty times production's.

What exists today is the deterministic event loop and the run identity built on it: the
totally-ordered queue, simulated time, the content-hashed `RunConfig`, and the trace two
runs are compared on -- plus the market-data source in `fking.backtest.feed`, which turns
the Parquet archive into that loop's event stream and refuses a window it cannot serve
without inventing bars, the cost model in `fking.backtest.costs`, and the overfitting gate
in `fking.backtest.validation`, which discounts an observed Sharpe by the number of
configurations searched to find it and refuses a search whose in-sample ranking carries no
out-of-sample information, and the walk-forward harness in `fking.backtest.walkforward`,
which schedules anchored and rolling re-fits with a purge and embargo derived from the
declared label horizon and reports out-of-sample performance as a decay slope rather than
a mean. The venue simulator and the portfolio metric suite arrive in their own pull
requests and hang off this loop.

Combinatorial purged cross-validation lives in `fking.backtest.cpcv` and is deliberately
*not* re-exported here. "Path" already means the equity path in this namespace --
`PathStatistics`, `path_economics` -- and in CPCV it means one combination of test groups;
hoisting `PathDistribution` and `path_distribution` alongside them would put two different
meanings of the word one line apart in `__all__`. Import the subpackage.

Trade-sequence bootstrap, block bootstrap and parameter perturbation live in
`fking.backtest.montecarlo`, for the same reason and the same treatment: a third sense of
"path" -- one Monte Carlo resampling -- stays out of this namespace. Import the
subpackage.

A backtest that is not bit-reproducible is not evidence, it is an anecdote with a number
attached -- so **a result that differs between two runs of the same `config_hash`
outranks everything else on the queue**. It is not a flake to be retried: until the
unseeded randomness or the clock read is found, nothing this engine has ever produced
can be trusted.

Everything not in `__all__` is private and may change without notice.
"""

from fking.backtest._clock import SimulationClock
from fking.backtest._config import (
    DEFAULT_EVENT_BUDGET,
    RunConfig,
    canonical_digest,
    config_hash,
    derive_seed,
)
from fking.backtest._engine import (
    FAILURE_DETAIL_LIMIT_BYTES,
    EventHandler,
    EventLoop,
    ExecutionOutcome,
    ExecutionReport,
    ExecutionReporter,
    RunContext,
    RunTrace,
    SpecRegistration,
    TraceEntry,
    failure_detail_for,
)
from fking.backtest._errors import (
    BacktestError,
    CausalityError,
    EventBudgetExhaustedError,
    ExecutionReportError,
    OversubscribedWorkersError,
    RunConfigError,
    UnregisteredSpecificationError,
)
from fking.backtest._events import (
    Event,
    EventPriority,
    FillEvent,
    FundingEvent,
    MarketDataEvent,
    OrderAckEvent,
    ReconciliationEvent,
    RejectEvent,
    TimerEvent,
)
from fking.backtest._queue import EventQueue, QueuedEvent
from fking.backtest._workers import (
    DEFAULT_PARENT_RESERVE_BYTES,
    WorkerMemoryBudget,
    container_memory_limit_bytes,
    resolve_worker_total,
)
from fking.backtest.costs import (
    MIN_EDGE_TO_COST_RATIO,
    CalibrationProvenanceError,
    CostBreakdown,
    CostModel,
    CostModelConfigError,
    CostModelError,
    CostTerm,
    CostVerdict,
    DepthProfile,
    DepthWalk,
    ExecutionLeg,
    FeeSchedule,
    FundingExposure,
    LatencyProfile,
    PartialFillProfile,
    RejectionReason,
    RoundTrip,
    RoundTripCost,
    RunCostReport,
    SpreadObservation,
    SpreadQuantile,
    SpreadQuantiles,
    SymbolSpreadProfile,
    assess_run,
    calibrate_spread_profile,
    charge_leg,
    charge_round_trip,
    walk_depth,
)
from fking.backtest.feed import (
    CoverageRefusedError,
    CoverageReport,
    FeedRequest,
    FeedSlice,
    MarketDataFeed,
    SeriesRequest,
    WarmupGate,
)
from fking.backtest.portfolio import (
    ANNUALISATION_DAYS,
    MIN_OBSERVATIONS_FOR_DISPERSION,
    MIN_OBSERVATIONS_FOR_EFFECTIVE_SAMPLE,
    MIN_REGIME_EFFECTIVE_SAMPLE,
    SECTION_ORDER,
    Credibility,
    DailyMark,
    EffectiveSample,
    EquityPath,
    EquityPathError,
    EquityPoint,
    LedgerTotals,
    MarkPriceMissingError,
    MetricInputError,
    PathEconomics,
    PathStatistics,
    PortfolioAccountingError,
    PortfolioError,
    PortfolioReport,
    PortfolioState,
    RegimeCoverage,
    RegimeSlice,
    ReportSection,
    RiskLimitBreachedError,
    RiskProfile,
    assemble_report,
    build_equity_path,
    effective_sample_or_none,
    effective_sample_size,
    path_economics,
    path_statistics,
    regime_breakdown,
    require_clean_result,
    risk_profile,
)
from fking.backtest.validation import (
    MAX_PROBABILITY_OF_BACKTEST_OVERFITTING,
    MIN_DEFLATED_SHARPE,
    OverfittingProbability,
    PathSplit,
    PathSplitMalformedError,
    SharpeEvidence,
    SharpeEvidenceUnusableError,
    TrialCountUnavailableError,
    ValidationGateError,
    ValidationRefusal,
    ValidationReport,
    assess_validation,
    deflated_sharpe_ratio,
    expected_max_sharpe,
    probability_of_backtest_overfitting,
)
from fking.backtest.walkforward import (
    MINIMUM_FOLDS,
    DecayPoint,
    DecayReport,
    DecayReportError,
    Fold,
    FoldEvaluationError,
    FoldFailure,
    OutOfSampleObservation,
    ScheduleRefusedError,
    WalkForwardConfigError,
    WalkForwardDeclaration,
    WalkForwardError,
    WalkForwardPlan,
    WalkForwardReport,
    WalkForwardSchedule,
    WalkForwardScheme,
    build_schedule,
    decay_report,
    run_walk_forward,
    schedule_table,
    segment_windows,
)

__all__ = [
    "ANNUALISATION_DAYS",
    "DEFAULT_EVENT_BUDGET",
    "DEFAULT_PARENT_RESERVE_BYTES",
    "FAILURE_DETAIL_LIMIT_BYTES",
    "MAX_PROBABILITY_OF_BACKTEST_OVERFITTING",
    "MINIMUM_FOLDS",
    "MIN_DEFLATED_SHARPE",
    "MIN_EDGE_TO_COST_RATIO",
    "MIN_OBSERVATIONS_FOR_DISPERSION",
    "MIN_OBSERVATIONS_FOR_EFFECTIVE_SAMPLE",
    "MIN_REGIME_EFFECTIVE_SAMPLE",
    "SECTION_ORDER",
    "BacktestError",
    "CalibrationProvenanceError",
    "CausalityError",
    "CostBreakdown",
    "CostModel",
    "CostModelConfigError",
    "CostModelError",
    "CostTerm",
    "CostVerdict",
    "CoverageRefusedError",
    "CoverageReport",
    "Credibility",
    "DailyMark",
    "DecayPoint",
    "DecayReport",
    "DecayReportError",
    "DepthProfile",
    "DepthWalk",
    "EffectiveSample",
    "EquityPath",
    "EquityPathError",
    "EquityPoint",
    "Event",
    "EventBudgetExhaustedError",
    "EventHandler",
    "EventLoop",
    "EventPriority",
    "EventQueue",
    "ExecutionLeg",
    "ExecutionOutcome",
    "ExecutionReport",
    "ExecutionReportError",
    "ExecutionReporter",
    "FeeSchedule",
    "FeedRequest",
    "FeedSlice",
    "FillEvent",
    "Fold",
    "FoldEvaluationError",
    "FoldFailure",
    "FundingEvent",
    "FundingExposure",
    "LatencyProfile",
    "LedgerTotals",
    "MarkPriceMissingError",
    "MarketDataEvent",
    "MarketDataFeed",
    "MetricInputError",
    "OrderAckEvent",
    "OutOfSampleObservation",
    "OverfittingProbability",
    "OversubscribedWorkersError",
    "PartialFillProfile",
    "PathEconomics",
    "PathSplit",
    "PathSplitMalformedError",
    "PathStatistics",
    "PortfolioAccountingError",
    "PortfolioError",
    "PortfolioReport",
    "PortfolioState",
    "QueuedEvent",
    "ReconciliationEvent",
    "RegimeCoverage",
    "RegimeSlice",
    "RejectEvent",
    "RejectionReason",
    "ReportSection",
    "RiskLimitBreachedError",
    "RiskProfile",
    "RoundTrip",
    "RoundTripCost",
    "RunConfig",
    "RunConfigError",
    "RunContext",
    "RunCostReport",
    "RunTrace",
    "ScheduleRefusedError",
    "SeriesRequest",
    "SharpeEvidence",
    "SharpeEvidenceUnusableError",
    "SimulationClock",
    "SpecRegistration",
    "SpreadObservation",
    "SpreadQuantile",
    "SpreadQuantiles",
    "SymbolSpreadProfile",
    "TimerEvent",
    "TraceEntry",
    "TrialCountUnavailableError",
    "UnregisteredSpecificationError",
    "ValidationGateError",
    "ValidationRefusal",
    "ValidationReport",
    "WalkForwardConfigError",
    "WalkForwardDeclaration",
    "WalkForwardError",
    "WalkForwardPlan",
    "WalkForwardReport",
    "WalkForwardSchedule",
    "WalkForwardScheme",
    "WarmupGate",
    "WorkerMemoryBudget",
    "assemble_report",
    "assess_run",
    "assess_validation",
    "build_equity_path",
    "build_schedule",
    "calibrate_spread_profile",
    "canonical_digest",
    "charge_leg",
    "charge_round_trip",
    "config_hash",
    "container_memory_limit_bytes",
    "decay_report",
    "deflated_sharpe_ratio",
    "derive_seed",
    "effective_sample_or_none",
    "effective_sample_size",
    "expected_max_sharpe",
    "failure_detail_for",
    "path_economics",
    "path_statistics",
    "probability_of_backtest_overfitting",
    "regime_breakdown",
    "require_clean_result",
    "resolve_worker_total",
    "risk_profile",
    "run_walk_forward",
    "schedule_table",
    "segment_windows",
    "walk_depth",
]
