"""Sizing, exposure limits, netting and the kill switch. Knows about signals,
exposure and capital.

This module holds sole authority to construct an `Order`. Everything upstream
proposes; this decides. It is pure for the same reason `strategy` is -- a risk
decision that depends on the wall clock cannot be replayed, and a risk decision that
cannot be replayed cannot be audited.
"""

from fking.risk._killswitch import (
    RECONCILIATION_FRESHNESS,
    REQUIRED_RECOVERY_STEP,
    KillSwitchError,
    KillSwitchGate,
    KillSwitchTrippedError,
    ResumePreconditions,
    ResumeRefusedError,
    TripPolicy,
    TripStep,
    arm,
    boot_halted_state,
    derive_state,
    derive_state_from,
    orders_to_cancel,
    resume,
    resume_refusals,
    trip,
    trip_sequence,
)
from fking.risk._state import (
    ARM_VALIDITY,
    HUMAN_OPERATOR_PREFIX,
    MIN_ROOT_CAUSE_LENGTH,
    ArmEvent,
    BookSnapshot,
    JournalRead,
    JournalReadOutcome,
    JournalUnreadable,
    KillSwitchEvent,
    KillSwitchState,
    KillSwitchStatus,
    ResumeEvent,
    TripEvent,
    TripTrigger,
)

__all__: tuple[str, ...] = (
    "ARM_VALIDITY",
    "HUMAN_OPERATOR_PREFIX",
    "MIN_ROOT_CAUSE_LENGTH",
    "RECONCILIATION_FRESHNESS",
    "REQUIRED_RECOVERY_STEP",
    "ArmEvent",
    "BookSnapshot",
    "JournalRead",
    "JournalReadOutcome",
    "JournalUnreadable",
    "KillSwitchError",
    "KillSwitchEvent",
    "KillSwitchGate",
    "KillSwitchState",
    "KillSwitchStatus",
    "KillSwitchTrippedError",
    "ResumeEvent",
    "ResumePreconditions",
    "ResumeRefusedError",
    "TripEvent",
    "TripPolicy",
    "TripStep",
    "TripTrigger",
    "arm",
    "boot_halted_state",
    "derive_state",
    "derive_state_from",
    "orders_to_cancel",
    "resume",
    "resume_refusals",
    "trip",
    "trip_sequence",
)
